### ISSUE TITLE
Circle CI and Download Page Question

### ISSUE THREAD

**Issue by ethsmith** [GlowstonePlusPlus/glowstoneplusplus.github.io#2]
I have never used Circle CI and i was just wondering, is there a specific reason why the download link on the website menu and the download button links to Circle CI instead of making a download page with a download button that is linked to a direct download of glowstone++?

**Comment by mastercoms** [comment]
CircleCI is our build system, like Jenkins. It is no different to linking to Jenkins. However, the download button on the homepage should be a direct download, and the downloads page should remain how it is. 

The reason why it is not right now is that CircleCI does not provide direct download links, and requires use of their API to do such a thing. I haven't gotten around to figuring out how to do this yet.

Closing this as I don't think it is an issue, but it should be something we keep in mind.

**Comment by ethsmith** [comment]
It was a question I had :+1:
