### ISSUE TITLE
GlowstonePlusPlus Domain

### ISSUE THREAD

**Issue by ethsmith** [GlowstonePlusPlus/glowstoneplusplus.github.io#5]
Do you have a domain for the website? Do you want me to buy one or do you have a plan?

**Comment by mastercoms** [comment]
I'm not sure our name should be Glowstone++ going forward. It should be more like Spigot is to CraftBukkit. There was a fork named CraftBukkit++, but it eventually became Spigot, which I think is what should happen to Glowstone++.

**Comment by ethsmith** [comment]
Yeah but we need one that fits and is easy to remember, gonna be hard to come up with a name that will represent this server software for the rest of it's time :P

**Comment by ethsmith** [comment]
Got any suggestions? xD

**Comment by ethsmith** [comment]
I will close this for now i guess

**Comment by mastercoms** [comment]
- Ignite
- Glow
- Light
- Phoenix

**Comment by ethsmith** [comment]
Lets go the sponge way and name it Blaze Powered xD and just have the Blaze Server and Blaze Forums with a domain BlazePowered.org :P lol

**Comment by mastercoms** [comment]
Blaze doesn't sound right

(:smoking:)

**Comment by ethsmith** [comment]
It was more a joke but yeah lol

**Comment by ethsmith** [comment]
I will try to think some good names up

**Comment by ethsmith** [comment]
GlowBukkit? xD Names are gonna be hard if we want to change it

**Comment by mastercoms** [comment]
GlowBukkit makes no sense. We don't support only bukkit plugins.

**Comment by ethsmith** [comment]
I know i was joking, have a sense of humor :P On a serious note, the name needs to represent what it does, or be a name that can be easily remembered and sound good to the community. We could go with your above idea and name it like Phoenix or Something, I wish it was easy, Do you think it would be smarter to worry about this now or later?

**Comment by mastercoms** [comment]
Ok, sorry, I can't really tell. It isn't very urgent now, but it needs to be done before Glowstone++ becomes popular.

**Comment by ethsmith** [comment]
ok :)

**Comment by mastercoms** [comment]
We're talking about getting the glowstone.net domain.

**Comment by mastercoms** [comment]
got it!

**Comment by ethsmith** [comment]
Sweet
